version: 2.1
jobs:
    build-recent:
        docker:
          - image: cimg/base:stable
            auth:
                username: mydockerhub-user
                password: $DOCKERHUB_PASSWORD
            environment:
                CMAKE_BUILD_TYPE: Release
                FLAGS: -Wall
                INSTALL: ~/externalRepo/opensmt
                EXTERNALREPODIR: externalRepo
                USE_READLINE: OFF
        steps:
            - checkout
            - run:
                name: apt-get update
                command: sudo apt-get update
            - run:
                name: Install Dependencies
                command: sudo apt-get install libgmp-dev libedit-dev bison flex cmake libubsan0
            
            - run:
                name: Install Sqllite
                command: sudo apt-get install zlib1g-dev libsqlite3-dev      
            - run: 
                name: Install external opensmt Tag V2.0.1
                command: sh ./ci/run_travis_opensmtCommands.sh
                environment:
                    CMAKE_BUILD_TYPE: Release
            - run:
                name: Create the build directory
                command: mkdir build
            - run:
                name: Release build gcc
                command: sh ./ci/run_travis_smtsCommands.sh
                environment:
                    CMAKE_BUILD_TYPE: Release
            - run:
                name: Debug build gcc
                command: sh ./ci/run_travis_smtsCommands.sh
                environment:
                    CMAKE_BUILD_TYPE: Debug
            - run:
                name: Clean build directory
                command: |
                    rm -rf build
                    mkdir build
            - run:
                name: Install clang
                command: |
                    sudo apt-get install clang
                    sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 60
            - run:
                name: Release build llvm
                command: sh ./ci/run_travis_smtsCommands.sh
                environment:
                    CMAKE_BUILD_TYPE: Release
            - run:
                name: Debug build llvm
                command: sh ./ci/run_travis_smtsCommands.sh
                environment:
                    CMAKE_BUILD_TYPE: Debug
                    FLAGS: -Wall -Werror=sign-compare -Wunused-lambda-capture -fsanitize=signed-integer-overflow
            - run:
                name: Run Server - Client
                command: sh ./runtest/run-server-client.sh      


workflows:
    build-test:
        jobs:
            - build-recent
